"""故障分类与状态枚举定义 — Module C Step 10."""

from enum import StrEnum


class FaultCategory(StrEnum):
    """网络故障分类枚举。"""

    COVERAGE_ISSUE = "COVERAGE_ISSUE"
    DROPPED_CONNECTION = "DROPPED_CONNECTION"
    HIGH_LATENCY = "HIGH_LATENCY"
    DNS_FAILURE = "DNS_FAILURE"
    AUTH_FAILURE = "AUTH_FAILURE"
    DEVICE_FAILURE = "DEVICE_FAILURE"
    WEAK_SIGNAL = "WEAK_SIGNAL"
    CONFIG_ERROR = "CONFIG_ERROR"
    PACKET_LOSS = "PACKET_LOSS"
    BANDWIDTH_DEGRADATION = "BANDWIDTH_DEGRADATION"
    SERVICE_OUTAGE = "SERVICE_OUTAGE"
    CUSTOMER_PREMISES_ISSUE = "CUSTOMER_PREMISES_ISSUE"
    UNKNOWN = "UNKNOWN"


class ReviewStatus(StrEnum):
    """人工复核状态枚举。"""

    PENDING = "PENDING"
    CONFIRMED = "CONFIRMED"
    CORRECTED = "CORRECTED"
    REJECTED = "REJECTED"


class BatchStatus(StrEnum):
    """批处理任务状态枚举。"""

    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    PARTIAL_FAILED = "PARTIAL_FAILED"
    FAILED = "FAILED"
